#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx-role

- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes
    state: started

- name: Deploy webpage
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
